### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by ignatandrei** [SzymonHalucha/Minerals.AutoInterfaces#1]
I maintain a list of Roslyn Code Generators at [ignatandrei.github.io/RSCG_Examples/v2/docs/rscg-examples](https://ignatandrei.github.io/RSCG_Examples/v2/docs/rscg-examples)

I see yours- but I need some examples in the readme to understand if your code is usable.

Could you provide ?
Thanks
Andrei

**Comment by SzymonHalucha** [comment]
Hello,
I am simultaneously developing three code generator packages (AutoInterfaces, AutoMixins, AutoCommands), I will probably add a detailed Readme with code examples for all my packages in the next few days

**Comment by SzymonHalucha** [comment]
I added descriptions with code samples to three packages (Minerals.AutoInterfaces, Minerals.AutoMixins, Minerals.AutoCommands)

**Comment by ignatandrei** [comment]
Thanks. 
I tried to make an example, but unfortunately it gives me an error:
"1>CSC : warning CS8785: Generator 'GenerateInterfaceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Enumeration has not started. Call MoveNext.'.
"
And it not generates files for interface, just for attribute
You can find the project attached for easy reproducing the problem.
Thanks!

[src.zip](https://github.com/SzymonHalucha/Minerals.AutoInterfaces/files/15174600/src.zip)

**Comment by SzymonHalucha** [comment]
I fixed the bug, it was related to the CodeBuilder class trying to get usings when there were no usings at all.

I also discovered and fixed a bug related to FileScopedNamespace, which was used in your example (it was not included in the generated file).

I added your example to the test project.

The new version (1.5) is now available on NuGet.

**Comment by ignatandrei** [comment]
It works!

https://ignatandrei.github.io/RSCG_Examples/v2/docs/Minerals.AutoInterfaces

For the other two, I will evaluate and come back
Thanks for your time!
Andrei
